services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=myproject
      - DATABASE_USER=myprojectuser
      - DATABASE_PASSWORD=myprojectpassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
